version: "3"
services:
  mopidy:
    container_name: mopidy
    image: joursain/raspberry-mopidy
    #build:
      #context: ..
      #dockerfile: media/mopidy/Dockerfile.mopidy
    ports:
      - "6680:6680"
    volumes:
      - ${MOPIDY_CONFIG}:/mnt/mopidy/config
      - ${MOPIDY_LOCAL}:/mnt/mopidy/local
    environment:
      - RA_UUID=1000
      - RA_GUID=1000
      - RA_SRVC=mopidy
      - RA_FLDR=/mnt/mopidy
    devices:
      - /dev/snd
    healthcheck:
#      test: ["CMD-SHELL", "curl -f http://spotify.etxe.local || bash -c 'kill -s 15 -1 && (sleep 10; kill -s 9 -1)'"]
      test: ["CMD-SHELL", "curl -f http://spotify.etxe.local || bash -c '/etc/init.d/mopidy restart'"]
      interval: 30m
      timeout: 10s
      retries: 3
      start_period: 45s
    restart: unless-stopped
  transmission:
    container_name: transmission
    image: joursain/raspberry-transmission
   #build:
     #context: ..
     #dockerfile: media/transmission/Dockerfile.transmission
    ports:
      - "9091:9091"
      - "51413:51413"
    volumes:
      - ${TRANSMISSION_CONFIG}:/mnt/transmission/config
      - ${TRANSMISSION_TEMP}:/mnt/transmission/temp
      - ${TRANSMISSION_DOWNLOAD}:/mnt/transmission/download
      - ${TRANSMISSION_WATCH}:/mnt/transmission/watch
    environment:
      - RA_UUID=1000
      - RA_GUID=1000
      - RA_SRVC=debian-transmission
      - RA_FLDR=/mnt/transmission
  plex:
    container_name: plex
    image: ghcr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
 #- PLEX_CLAIM= see .env file  
    volumes:
      - ${PLEX_CONFIG}:/config
   #- /mnt/media/plex/tv:/tv      
      - ${PLEX_MOVIES}:/movies
    restart: unless-stopped
