# 0. Official armv32 image
FROM debian:buster-slim

LABEL "guru.raraavis.creator"="blog@raraavis.guru"
LABEL "guru.raraavis.version"="2.0.0"
LABEL "guru.raraavis.release-date"="25/09/2022"
LABEL "guru.raraavis.description"="Raspberry Pi 3 image with Mopidy"

# 1. Environment vars
ARG DEBIAN_FRONTEND=noninteractive
ARG TZ=Europe/Madrid
ENV TZ=$TZ
	# Use 1 for headphones, 0 for HDMI
ARG AUDIO=1

# 2. Update system and install necessary packages
RUN	apt-get update && \
	apt-get install -y \
		wget \
		lsb-release \
		gnupg2 \
		gnupg \
		gnupg1 \
		python3-dev \
		python3-pip \
		libffi-dev \
		curl \
		cron \
		gosu \
		sudo \
		dumb-init && \
                rm -rf /var/lib/apt/lists/* && \
                rm -rf /tmp/*

# 3. Add mopidy repository
RUN	mkdir -p /usr/local/share/keyrings
RUN	wget -q -O /usr/local/share/keyrings/mopidy-archive-keyring.gpg  https://apt.mopidy.com/mopidy.gpg
RUN	wget -q -O /etc/apt/sources.list.d/mopidy.list https://apt.mopidy.com/buster.list

# 4. Install pip packages and Mopidy
RUN	apt-get update && \
	apt-get install -y \
		mopidy \
		libspotify-dev && \
        rm -rf /var/lib/apt/lists/* && \
        rm -rf /tmp/*
RUN	python3 -m pip install \
		pyspotify \
		Mopidy-Local \
		Mopidy-Iris \
		Mopidy-Mobile \
		Mopidy-Spotify \
		Mopidy-Mopify

# 5. Configure user
RUN     usermod -d /mnt/mopidy mopidy
RUN	echo "mopidy ALL=NOPASSWD: /usr/local/lib/python3.7/dist-packages/mopidy_iris/system.sh" >> /etc/sudoers

# 6. Create folders
WORKDIR /mnt/mopidy
RUN	mkdir /mnt/mopidy/data
RUN	mkdir /mnt/mopidy/cache
RUN	mkdir /mnt/mopidy/logs
COPY    scripts/ scripts/

# 7. Configuration local scan
RUN	(crontab -l 2>/dev/null || true; echo "0 */1 * * * mopidy --config /mnt/mopidy/config/mopidy.conf local scan") | crontab -
RUN	ln -sf /mnt/mopidy/config/mopidy.conf /etc/mopidy/mopidy.conf

# 8. Audio settings
RUN	echo		\
"pcm.!default {		\n\
  type asym		\n\	
  playback.pcm {	\n\
  type plug		\n\
  slave.pcm "output"	\n\
}			\n\
capture.pcm {		\n\
  type plug		\n\
  slave.pcm "input"	\n\
  }			\n\
}			\n\
pcm.output {		\n\
  type hw		\n\
  card $AUDIO		\n\
}			\n\	
ctl.!default {		\n\
  type hw		\n\
  card $AUDIO		\n\
}" >> /etc/asound.conf


# 9. Container
EXPOSE	6680
VOLUME	/mnt/mopidy/config
VOLUME	/mnt/mopidy/local

ENTRYPOINT ["/usr/bin/dumb-init","--"]
CMD ["/bin/sh", "scripts/entry_point.sh", "mopidy", "--config", "/mnt/mopidy/config/mopidy.conf"]
